services:
  - type: web
    name: ai-ids
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=10000 --server.address=0.0.0.0
    envVars:
      - key: STREAMLIT_SERVER_HEADLESS
        value: true